### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([15, 55, 75, 84, 63,  3, 72, 84, 67, 19,  8, 80, 23, 46, 72])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[99, 32, 56, 84],
       [32, 43, 23, 74],
       [24, 45, 85, 37],
       [30,  8, 85, 40],
       [28, 61,  4, 64],
       [32,  2, 86, 81]])

In [7]:
np.sort(a) # asce order

array([ 3,  8, 15, 19, 23, 46, 55, 63, 67, 72, 72, 75, 80, 84, 84])

In [5]:
np.sort(a)[::-1] # desc order

array([84, 84, 80, 75, 72, 72, 67, 63, 55, 46, 23, 19, 15,  8,  3])

In [15]:
np.sort(b, axis =1)

array([[32, 56, 84, 99],
       [23, 32, 43, 74],
       [24, 37, 45, 85],
       [ 8, 30, 40, 85],
       [ 4, 28, 61, 64],
       [ 2, 32, 81, 86]])

In [16]:
np.sort(b,axis=0)

array([[24,  2,  4, 37],
       [28,  8, 23, 40],
       [30, 32, 56, 64],
       [32, 43, 85, 74],
       [32, 45, 85, 81],
       [99, 61, 86, 84]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [11]:
# code
np.append(a,200)

array([ 15,  55,  75,  84,  63,   3,  72,  84,  67,  19,   8,  80,  23,
        46,  72, 200])

In [12]:
b

array([[99, 32, 56, 84],
       [32, 43, 23, 74],
       [24, 45, 85, 37],
       [30,  8, 85, 40],
       [28, 61,  4, 64],
       [32,  2, 86, 81]])

In [14]:
np.append(b,np.ones((b.shape[0],1)) , axis = 1)

array([[99., 32., 56., 84.,  1.],
       [32., 43., 23., 74.,  1.],
       [24., 45., 85., 37.,  1.],
       [30.,  8., 85., 40.,  1.],
       [28., 61.,  4., 64.,  1.],
       [32.,  2., 86., 81.,  1.]])

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[12.        , 52.        , 42.        ,  6.        ,  0.22006275],
       [29.        , 18.        , 47.        , 55.        ,  0.81740634],
       [61.        , 93.        , 83.        ,  9.        ,  0.89146072],
       [38.        , 63.        , 44.        , 85.        ,  0.84519124],
       [ 8.        , 87.        , 31.        , 72.        ,  0.24007274],
       [40.        , 71.        ,  2.        ,  7.        ,  0.48056374]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [17]:
# code-> exactly like stacking but much better approach
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [18]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [20]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [21]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [22]:
# code
a.shape

(15,)

In [23]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [24]:
np.expand_dims(a,axis=1)

array([[15],
       [55],
       [75],
       [84],
       [63],
       [ 3],
       [72],
       [84],
       [67],
       [19],
       [ 8],
       [80],
       [23],
       [46],
       [72]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [25]:
a

array([15, 55, 75, 84, 63,  3, 72, 84, 67, 19,  8, 80, 23, 46, 72])

In [30]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  2,  3,  4,  6,  7,  8, 11, 14]),)

In [27]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([15,  0,  0,  0,  0,  3,  0,  0,  0, 19,  8,  0, 23, 46,  0])

In [31]:
np.where(a%2 == 0,0,a)

array([15, 55, 75,  0, 63,  3,  0,  0, 67, 19,  0,  0, 23,  0,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [32]:
# code
a

array([15, 55, 75, 84, 63,  3, 72, 84, 67, 19,  8, 80, 23, 46, 72])

In [33]:
np.argmax(a)

np.int64(3)

In [34]:
b

array([[99, 32, 56, 84],
       [32, 43, 23, 74],
       [24, 45, 85, 37],
       [30,  8, 85, 40],
       [28, 61,  4, 64],
       [32,  2, 86, 81]])

In [35]:
np.argmax(b,axis=0)

array([0, 4, 5, 0])

In [36]:
np.argmax(b,axis=1)

array([0, 3, 2, 2, 3, 2])

In [37]:
# np.argmin
np.argmin(a)

np.int64(5)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [38]:
a

array([15, 55, 75, 84, 63,  3, 72, 84, 67, 19,  8, 80, 23, 46, 72])

In [39]:
np.cumsum(a)

array([ 15,  70, 145, 229, 292, 295, 367, 451, 518, 537, 545, 625, 648,
       694, 766])

In [40]:
b

array([[99, 32, 56, 84],
       [32, 43, 23, 74],
       [24, 45, 85, 37],
       [30,  8, 85, 40],
       [28, 61,  4, 64],
       [32,  2, 86, 81]])

In [41]:
np.cumsum(b,axis=1)

array([[ 99, 131, 187, 271],
       [ 32,  75,  98, 172],
       [ 24,  69, 154, 191],
       [ 30,  38, 123, 163],
       [ 28,  89,  93, 157],
       [ 32,  34, 120, 201]])

In [42]:
np.cumsum(b)

array([  99,  131,  187,  271,  303,  346,  369,  443,  467,  512,  597,
        634,  664,  672,  757,  797,  825,  886,  890,  954,  986,  988,
       1074, 1155])

In [43]:
# np.cumprod
np.cumprod(a)

array([                  15,                  825,                61875,
                    5197500,            327442500,            982327500,
                70727580000,        5941116720000,      398054820240000,
           7563041584560000,    60504332676480000,  4840346614118400000,
         647507682465890304, -7108134753988149248,  4723131776720699392])

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [44]:
a

array([15, 55, 75, 84, 63,  3, 72, 84, 67, 19,  8, 80, 23, 46, 72])

In [45]:
np.percentile(a,50)

np.float64(63.0)

In [46]:
np.median(a)

np.float64(63.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [47]:
# code
a

array([15, 55, 75, 84, 63,  3, 72, 84, 67, 19,  8, 80, 23, 46, 72])

In [48]:
np.histogram(a,bins=[0,50,100])

(array([6, 9]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [49]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [50]:
# code
a


array([15, 55, 75, 84, 63,  3, 72, 84, 67, 19,  8, 80, 23, 46, 72])

In [51]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([80])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [52]:
# code
a

array([15, 55, 75, 84, 63,  3, 72, 84, 67, 19,  8, 80, 23, 46, 72])

In [53]:
np.flip(a)

array([72, 46, 23, 80,  8, 19, 67, 84, 72,  3, 63, 84, 75, 55, 15])

In [54]:
b

array([[99, 32, 56, 84],
       [32, 43, 23, 74],
       [24, 45, 85, 37],
       [30,  8, 85, 40],
       [28, 61,  4, 64],
       [32,  2, 86, 81]])

In [55]:
np.flip(b,axis=1)

array([[84, 56, 32, 99],
       [74, 23, 43, 32],
       [37, 85, 45, 24],
       [40, 85,  8, 30],
       [64,  4, 61, 28],
       [81, 86,  2, 32]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [56]:
# code
a

array([15, 55, 75, 84, 63,  3, 72, 84, 67, 19,  8, 80, 23, 46, 72])

In [57]:
np.put(a,[0,1],[110,530])

In [58]:
a

array([110, 530,  75,  84,  63,   3,  72,  84,  67,  19,   8,  80,  23,
        46,  72])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [59]:
# code
a

array([110, 530,  75,  84,  63,   3,  72,  84,  67,  19,   8,  80,  23,
        46,  72])

In [60]:
np.delete(a,[0,2,4])

array([530,  84,   3,  72,  84,  67,  19,   8,  80,  23,  46,  72])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [61]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [62]:
np.intersect1d(m,n)

array([3, 4, 5])

In [63]:
np.setdiff1d(m,n)

array([1, 2])

In [64]:
np.setdiff1d(n,m)

array([6, 7])

In [66]:
np.setxor1d(m,n) # will remove common elements

array([1, 2, 6, 7])

In [68]:
m[np.in1d(m,1)]

/tmp/ipykernel_7693/524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [69]:
# code
a

array([110, 530,  75,  84,  63,   3,  72,  84,  67,  19,   8,  80,  23,
        46,  72])

In [70]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 75, 63, 25, 72, 75, 67, 25, 25, 75, 25, 46, 72])

In [71]:
# 17. np.swapaxes

In [72]:
# 18. np.uniform

In [73]:
# 19. np.count_nonzero

In [74]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [75]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [76]:

# 23. np.allclose and equals